// Sub-batch 2 mega-pass — §5.5 cohort (Audits and Pen Tests): 5 cohort items, 5 modified.
//
// 0 Convention B holdbacks.
//
// 0 rebuild.
//
// 2 multi-pad:
//   - mc-5.5.1-0  External vs internal audit
//   - mc-5.5.2-1  Post-exploitation
//
// 3 simple-pad:
//   - mc-5.5.1-1  Attestation
//   - mc-5.5.2-0  PCI DSS pen test cadence
//   - mc-5.5.2-2  Remediation validation
//
// Watchpoints respected:
//   - Internal audit (independence by reporting line) vs external audit (third-party
//     independence, more credible to regulators/customers/investors).
//   - Attestation = formal declaration of control existence and operating effectiveness.
//   - PCI DSS pen test cadence: annual + after significant changes.
//   - Pen-test phases: reconnaissance → enumeration → exploitation → post-exploitation
//     (lateral movement, privilege escalation, data reach) → reporting.
//   - Remediation validation = retest after fix to confirm the vulnerability is closed.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..");
const jsonPath = resolve(repo, "questions.json");
const previewPath = "/tmp/questions-d5.5-distractor-preview.json";

const args = process.argv.slice(2);
const write = args.includes("--write");
const preview = args.includes("--preview");

const data = JSON.parse(readFileSync(jsonPath, "utf8"));

export const REPLACEMENTS = [
  {
    videoId: "5.5.1", kind: "mc", index: 0,
    expectedOldStemPrefix: "The primary advantage of an external audit over an internal audit is",
    intensity: "multi-pad",
    newOpts: [
      "External audits are cheaper than internal audits because there is no in-house staffing cost",         // 96
      "External auditors have better automated tooling than internal teams typically can deploy in-house",     // 99
      "External auditors are independent — their assessment is more credible to regulators, customers, and investors",  // ✓ 109
      "Internal audits take longer than external audits because internal teams have more institutional context",  // 105
    ],
  },
  {
    videoId: "5.5.1", kind: "mc", index: 1,
    expectedOldStemPrefix: "Attestation in the audit context means",
    intensity: "simple-pad",
    newOpts: [
      "Physically witnessing an audit on-site by sitting alongside the auditor during fieldwork days",       // 96
      "A formal declaration — either by management or an independent auditor — that controls are implemented and operating effectively",  // ✓ 127
      "An automated scan result generated by the vulnerability scanner against in-scope production systems",  // 100
      "An informal conversation about security controls during the auditor's annual on-site visit week",      // 99
    ],
  },
  {
    videoId: "5.5.2", kind: "mc", index: 0,
    expectedOldStemPrefix: "PCI DSS requires penetration testing",
    intensity: "simple-pad",
    newOpts: [
      "Only when a breach occurs and the acquirer demands a forensic post-incident review",                   // 84
      "Only if the organization processes over 1 million transactions per year through the acquiring bank",     // 100
      "Annually and after any significant changes to the environment — testing both internal and external perspectives",  // ✓ 111
      "Only for external-facing systems within the cardholder data environment defined in scope",                // 95
    ],
  },
  {
    videoId: "5.5.2", kind: "mc", index: 1,
    expectedOldStemPrefix: "Post-exploitation demonstrates",
    intensity: "multi-pad",
    newOpts: [
      "What an attacker can do AFTER gaining initial access — lateral movement, privilege escalation, and what data they could reach",  // ✓ 125
      "That the vulnerability exists in the first place by confirming the precondition through fingerprinting",                          // 102
      "How the initial compromise occurred by reconstructing the entry vector and exploitation chain in detail",                          // 102
      "How to fix the vulnerability by walking the developer through a recommended secure coding pattern",                                  // 96
    ],
  },
  {
    videoId: "5.5.2", kind: "mc", index: 2,
    expectedOldStemPrefix: "Remediation validation (retesting) after a pen test is important because",
    intensity: "simple-pad",
    newOpts: [
      "It provides another revenue opportunity for testers and so should be skipped to control engagement cost",  // 105
      "It confirms the vulnerability was actually fixed — patches can be misapplied or incomplete",                 // ✓ 90
      "It is always required by regulations regardless of the original test scope or risk register entries",         // 100
      "It generates a new report that supersedes the original engagement findings document entirely",               // 92
    ],
  },
];

let applied = 0, skipped = 0, refused = 0;
const log = [];
for (const r of REPLACEMENTS) {
  const sec = data.find((s) => s.id === r.videoId.split(".").slice(0, 2).join("."));
  if (!sec) { console.error(`section not found for ${r.videoId}`); refused++; continue; }
  const vid = sec.videos.find((v) => v.id === r.videoId);
  if (!vid) { console.error(`video not found for ${r.videoId}`); refused++; continue; }
  const list = r.kind === "mc" ? vid.questions : vid.scenarios;
  const item = list?.[r.index];
  if (!item) { console.error(`item not found at ${r.videoId} ${r.kind}[${r.index}]`); refused++; continue; }
  if (!item.q.startsWith(r.expectedOldStemPrefix)) {
    console.error(`REFUSING ${r.videoId} ${r.kind}[${r.index}] — stem mismatch`);
    refused++; continue;
  }
  const sameOpts = r.newOpts.length === item.opts.length && r.newOpts.every((o, i) => o === item.opts[i]);
  if (sameOpts) { skipped++; continue; }
  const currentCorrect = item.opts[item.a];
  if (!r.newOpts.includes(currentCorrect)) {
    console.error(`REFUSING ${r.videoId} ${r.kind}[${r.index}] — current correct option not in newOpts`);
    refused++; continue;
  }
  const newA = r.newOpts.indexOf(currentCorrect);
  log.push({ qid: `${r.kind}-${r.videoId}-${r.index}`, intensity: r.intensity, oldOpts: item.opts.slice(), newOpts: r.newOpts, oldA: item.a, newA });
  if (write || preview) { item.opts = r.newOpts.slice(); item.a = newA; }
  applied++;
}

console.log(`\n§5.5 fix plan ${write ? "(APPLY mode)" : preview ? "(PREVIEW mode)" : "(DRY-RUN)"}`);
console.log(`Total REPLACEMENTS: ${REPLACEMENTS.length} (0 holdbacks)`);
console.log(`  applied:  ${applied}`);
console.log(`  skipped (idempotent): ${skipped}`);
console.log(`  refused (safety): ${refused}`);
const intensityCounts = {};
for (const l of log) intensityCounts[l.intensity] = (intensityCounts[l.intensity] || 0) + 1;
console.log(`Intensity:`, intensityCounts);

if (write || preview) {
  const target = write ? jsonPath : previewPath;
  writeFileSync(target, JSON.stringify(data, null, 2) + "\n");
  console.log(`Wrote to ${target}`);
}
